name: Main Pipeline

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Build & Deploy to Docker registry (CI)
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/superior-rewards-api:main
          builder: ${{ steps.buildx.outputs.name }}
          cache-from: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/superior-rewards-api:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/superior-rewards-api:buildcache,mode=max

  deploy:
    runs-on: ubuntu-latest
    needs: [build]

    steps:
      - uses: actions/checkout@v3
      - name: SSH and deploy node app (CD)
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            sudo docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}
            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/superior-rewards-api:main
            sudo docker rm -f superior-rewards-api-container
            sudo docker run -d --name superior-rewards-api-container --net="host" -e "NODE_ENVIRONMENT=production" --restart always ${{ secrets.DOCKER_USERNAME }}/superior-rewards-api:main
            sudo docker image prune -f -a --filter "until=24h"
            exit 0
